pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
- script: npm install
- script: npm run build
- task: PublishBuildArtifact@1
  inputs:
    PathtoPublish: '${System.DefaultWorkingDirectory}/dist'
