pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
- script: npm install
- script: npm run build
- task: AzureKeyVault@1
  inputs:
    azureSubscription: ServiceConnection1
    keyVaultName: timetrackingappkeyvault
    secretsFilter: '*'
    runAsPreJob: false
- script: az storage blob upload-batch - account-name timetrackingstorageacct --account-key $storageAccountKey - destination `$web` - source ./dist