pool:
  vmImage: 'ubuntu-latest'
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '12.x'
- script: npm install
- script: npm run build
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: 'dist'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
